# Generated by Django 4.2.7 on 2025-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contracts_contract',
        ),
    ]
