version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://postgres:Super_16.com@qcymrajsokxnmyzqolxh.supabase.co:5432/postgres?sslmode=require
    depends_on:
      - redis

  redis:
    image: redis:alpine

volumes:
  postgres_data:
